export class EmployeeDetail {
  Detail_Id!: number;
  Branch_Sno!: number;
  Emp_Id_No!: string;
  Full_Name!: string;
  Branch_Name!: string | null;
  First_Name!: string;
  Middle_name!: string;
  Last_name!: string;
  Desg_name!: string;
  User_name!: string;
  Loc_Name!: string | null;
  Flag!: string | null;
  C_time!: string;
  Desg_Id!: number;
  Email_Address!: string;
  Password!: string;
  Mobile_No!: string;
  Created_Date!: string;
  Expiry_Date!: string;
  F_Login!: string;
  SNO!: number;
  Q_Name!: string | null;
  Q_Ans!: string | null;
  App_Status!: string | null;
  Log_Att!: number;
  Log_Time!: string | null;
  Log_Status!: string | null;
  Emp_Status!: string;
  AuditBy!: string;
  Audit_Date!: string;
}
