export class Company {
  CompSno!: number;
  Sus_Ac_SNo!: number;
  Sus_Acc!: null | string;
  CompName!: string;
  Status!: string;
  PostBox!: string;
  Address!: string;
  RegId!: number;
  DistSno!: number;
  WardSno!: number;
  RegName!: null | string;
  DistName!: null | string;
  WardName!: null | string;
  TinNo!: string;
  VatNo!: string;
  DirectorName!: string;
  Email!: string;
  TelNo!: string;
  FaxNo!: string;
  MobNo!: string;
  CompLogo!: null;
  DirectorSig!: null;
  Postedby!: null;
  Posteddate!: string;
  BankSno!: number;
  CompanySno!: number;
  Branch_Sno!: number;
  BankName!: null | string;
  BankBranch!: null | string;
  AccountNo!: null | string;
  Swiftcode!: null | string;
  Checker!: string;
}
