export enum TransactionDetailsTableHeadersMap {
  ID,
  PAYMENT_DATE,
  INVOICE_NUMBER,
  TOTAL_AMOUNT,
  PAID_AMOUNT,
  BALANCE,
  CONTROL_NUMBER,
  PAYMENT_TYPE,
  PAYMENT_METHOD,
  TRANSACTION_NUMBER,
  RECEIPT_NUMBER,
}
