export class GeneratedInvoice {
  Inv_Mas_Sno!: number;
  Inv_Det_Sno!: number;
  Invoice_Date!: string;
  Payment_Type!: string;
  Invoice_No!: string;
  Due_Date!: string;
  Invoice_Expired_Date!: string;
  Chus_Mas_No!: number;
  Chus_Name!: string;
  Com_Mas_Sno!: number;
  Cmpny_Name!: string;
  Company_Name!: string;
  Inv_Remarks!: string | null;
  Remarks!: string;
  vat_category!: string | null;
  Currency_Code!: string;
  Currency_Name!: string;
  Total_Without_Vt!: number;
  Total_Vt!: number;
  Total!: number;
  Item_Qty!: number;
  Item_Unit_Price!: number;
  Item_Total_Amount!: number;
  Vat_Percentage!: number;
  Vat_Amount!: number;
  Item_Without_vat!: number;
  Item_Description!: string | null;
  AuditBy!: string | null;
  warrenty!: string;
  Vat_Type!: string | null;
  goods_status!: string;
  delivery_status!: string;
  Audit_Date!: Date;
  grand_count!: number;
  daily_count!: number;
  approval_status!: string;
  approval_date!: Date;
  p_date!: Date;
  Customer_ID_Type!: string | null;
  Customer_ID_No!: string | null;
  Zreport_Sno!: number;
  Zreport_Status!: string | null;
  Zreport_Status1!: string | null;
  Zreport_Date!: Date;
  Zreport_Date1!: Date | null;
  Zreport_Date2!: Date | null;
  Control_No!: string | null;
  Reason!: string | null;
  details!: GeneratedInvoice[] | null;
}
