// export class InvoiceReport {
//   Inv_Mas_Sno!: number;
//   Inv_Det_Sno!: number;
//   Invoice_Date!: string;
//   Payment_Type!: any;
//   Invoice_No!: string;
//   Due_Date!: any;
//   Invoice_Expired_Date!: any;
//   Chus_Mas_No!: number;
//   Chus_Name!: string;
//   Com_Mas_Sno!: number;
//   Cmpny_Name!: any;
//   Inv_Remarks!: any;
//   Remarks!: any;
//   vat_category!: any;
//   Currency_Code!: any;
//   Currency_Name!: any;
//   Total_Without_Vt!: number;
//   Total_Vt!: number;
//   Total!: number;
//   Item_Qty!: number;
//   Item_Unit_Price!: number;
//   Item_Total_Amount!: number;
//   Vat_Percentage!: number;
//   Vat_Amount!: number;
//   Item_Without_vat!: number;
//   Item_Description!: any;
//   AuditBy!: any;
//   warrenty!: string;
//   Vat_Type!: any;
//   goods_status!: string;
//   delivery_status!: string;
//   Audit_Date!: string;
//   grand_count!: any;
//   daily_count!: any;
//   approval_status!: any;
//   approval_date!: string;
//   p_date!: string;
//   Customer_ID_Type!: string;
//   Customer_ID_No!: string;
//   Zreport_Sno!: number;
//   Zreport_Status!: any;
//   Zreport_Status1!: any;
//   Zreport_Date!: string;
//   Zreport_Date1!: any;
//   Zreport_Date2!: any;
//   Control_No!: any;
//   Reason!: any;
// }

export class InvoiceReport {
  Inv_Mas_Sno!: number;
  Inv_Det_Sno!: number;
  Invoice_Date!: string;
  Payment_Type!: string;
  Invoice_No!: string;
  Due_Date!: string;
  Invoice_Expired_Date!: string;
  Chus_Mas_No!: number;
  Chus_Name!: string;
  Com_Mas_Sno!: number;
  Company_Name!: string;
  Inv_Remarks!: string;
  Remarks!: string | null;
  vat_category!: string | null;
  Currency_Code!: string;
  Currency_Name!: string | null;
  Total_Without_Vt!: number;
  Total_Vt!: number;
  Total!: number;
  Item_Qty!: number;
  Item_Unit_Price!: number;
  Item_Total_Amount!: number;
  Vat_Percentage!: number;
  Vat_Amount!: number;
  Item_Without_vat!: number;
  Item_Description!: string | null;
  AuditBy!: string | null;
  warrenty!: string | null;
  Vat_Type!: string | null;
  goods_status!: string;
  delivery_status!: string | null;
  Audit_Date!: string;
  grand_count!: number | null;
  daily_count!: number | null;
  approval_status!: string;
  approval_date!: string | null;
  p_date!: string;
  Customer_ID_Type!: string | null;
  Customer_ID_No!: string | null;
  Zreport_Sno!: number;
  Zreport_Status!: string | null;
  Zreport_Status1!: string | null;
  Zreport_Date!: string | null;
  Zreport_Date1!: string | null;
  Zreport_Date2!: string | null;
  Control_No!: string;
  Reason!: string | null;
}
