export class InvoiceConsolidatedReport {
  Inv_Mas_Sno!: number;
  Inv_Det_Sno!: number;
  Invoice_Date!: string | null;
  Payment_Type!: string | null;
  Invoice_No!: string | null;
  Due_Date!: string | null;
  Invoice_Expired_Date!: string | null;
  Chus_Mas_No!: number;
  Chus_Name!: string | null;
  Com_Mas_Sno!: number;
  Company_Name!: string | null;
  Customer_Name!: string | null;
  Inv_Remarks!: string | null;
  Remarks!: string | null;
  vat_category!: string | null;
  Currency_Code!: string | null;
  Currency_Name!: string | null;
  Invoice_Amount!: number;
  Amment_Amount!: number;
  Total!: number;
  Item_Qty!: number;
  AuditBy!: string | null;
  Reason!: string | null;
  goods_status!: string | null;
  delivery_status!: string | null;
  Audit_Date!: string;
  p_date!: string;
  Inv_Can_No!: number;
  Inv_Amm_No!: number;
  Cust_Mas_No!: number;
  Control_No!: string | null;
  vendor_id!: number;
  vendor!: string;
  no_of_payments!: number | null;
  receipt_amount!: number | null;
  branch_sno!: number;
  branch!: string;
  no_of_invoices!: number;
  invoice_amount!: number;
}
