export class TransactionDetail {
  SNO!: number;
  Balance!: number;
  Payment_SNo!: string;
  Payment_Date!: string;
  Payment_Type!: string;
  Amount_Type!: string;
  Payer_Name!: string;
  Payment_Trans_No!: string;
  Currency!: string | null;
  Invoice_Amount!: number;
  Invoice_Amount_Local!: number;
  Receipt_No!: string;
  Batch_No!: string | null;
  Remarks!: string | null;
  Authorize_Id!: string | null;
  Secure_Hash!: string | null;
  Response_Code!: string | null;
  Merchant!: string | null;
  Message!: string | null;
  Card!: string | null;
  Token!: string | null;
  Status!: string;
  Response!: string | null;
  Audit_Date!: string | null;
  AuditAction!: string | null;
  AuditDone!: string | null;
  AuditID!: number;
  PaidAmount!: number;
  ModifiedAmount!: number;
  Amount30!: number;
  Amount70!: number;
  BOT!: number;
  AcademicSno!: number;
  Acad_Year!: string | null;
  Col1!: string | null;
  Col2!: string | null;
  Col3!: string | null;
  Term_Type!: string | null;
  Fee_Sno!: number;
  Term_Sno!: number;
  Payment_Time!: string;
  Approve_Date!: string | null;
  Fee_Data_Sno!: string | null;
  Currency_Code!: string;
  Requested_Amount!: number;
  Payment_Desc!: string;
  Payer_Id!: string | null;
  Trans_Channel!: string;
  PR_WB_ID!: string | null;
  Institution_ID!: string;
  Control_No!: string;
  Chksum!: string | null;
  Charge_Type!: string | null;
  Invoice_Sno!: string;
  Currency_Type!: string | null;
  Posted_By!: string;
  Approved_By!: string | null;
  Posted_Date!: string;
  Amount!: number;
  Surcharge_Fee!: number;
  Examined!: string | null;
  Authorized!: string | null;
  Receipt_No_Service!: number;
  Comp_Mas_Sno!: number;
  Company_Name!: string | null;
  Cust_Mas_Sno!: number;
  Customer_Name!: string;
  Class_Sno!: number;
  Class_Name!: string | null;
  Section_Sno!: number;
  Section_Name!: string | null;
  Comp_Mas_SNO!: number;
  Cust_Mas_SNO!: number;
  Item_Total_Amount!: number;
  Error_Text!: string | null;
}
